GET http://127.0.0.1:8000/api/user
Accept: application/json
Authorization: Bearer 4|IWUGrdGnSS7eCsvno5iTiug09xXubGnFk17O54407d5c9494
### Guardar

POST http://127.0.0.1:8000/api/user
Accept: application/json
Content-Type: application/json

{
    "name":"rodrigo",
    "email": "rodri@gmail.com",
    "password": "rodrigo123"
}

### Mostrar

GET http://127.0.0.1:8000/api/user/1
Accept: application/json

### Modificar

PUT http://127.0.0.1:8000/api/user/2
Accept: application/json
Content-Type: application/json


{
  "name": "ana modificado",
  "email": "ana.mod@gmail.com",
  "password": "ana4321"
}

### eliminar usuario

DELETE http://127.0.0.1:8000/api/user/5
